<?php
/** @var \HuyNgo\WeatherModule\Block\WeatherBlock $block */
?>
<?php
    $result = $block->getWeatherInformation();
    $place = $result->name;
    $main = $result->weather[0]['main'];
    $description = $result->weather[0]['description'];
    $temp = $result->main['temp'];
    $temp_min = $result->main['temp_min'];
    $temp_max = $result->main['temp_max'];
    $umid = $result->main['humidity'];
    $feels_like = $result->main['feels_like'];
    $icon = $result->weather[0]['icon'];
    $pressure = $result->main['pressure'];
    $windspeed = $result->wind['speed'];
    $country = $result->sys['country'];
?>

<div style="margin:auto; width: 50%; padding: 10px; text-align: center;"><div id="show_weather"></div><div id="icon" style="margin: auto;"><img id="wicon" src="" alt="Weather icon"></div><div id="more_weather"></div></div>
<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
                var iconurl = '<?php echo "http://openweathermap.org/img/w/$icon.png" ?>';
                var info = '<?php echo "<h2>Thời tiết hiện tại của $place là $description.</h2>";?>';
                var more = '<?php echo "Nhiệt độ hiện tại: <b>$temp °C</b><br>Nhiệt độ thấp nhất: <b>$temp_min °C</b>, nhiệt độ cao nhất: <b>$temp_max °C</b>" . '<br>' .
                    "Độ ẩm: <b>$umid%</b><br>Tốc độ gió: <b>$windspeed m/s</b><br>Áp suất: <b>$pressure hPa</b>"; ?>';
                $('#show_weather').html(info);
                $('#more_weather').html(more);
                $('#wicon').attr('src', iconurl);
        });
    });
</script>

